
- platform: mqtt
  name: "Door Garage"
  state_topic: "garage/door/1/status"
  payload_on: "open"
  payload_off: "closed"
  availability_topic: "GarHAge/availability"
  device_class: garage_door
  qos: 0

- platform: mqtt
  state_topic: "frontdoor/cam"
  sensor_class: motion
  name: Front Door Motion

- platform: template
  sensors:
    house_status:
      friendly_name: 'House Status'
      value_template: >-
        {{ is_state('binary_sensor.rob_home', 'on') or is_state('binary_sensor.kristen_home', 'on') }}
      icon_template: >-
        {% if is_state('binary_sensor.rob_home', 'on') or is_state('binary_sensor.kristen_home', 'on') %}
          mdi:home
        {% else %}
          mdi:airplane
        {% endif %}

