homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      hide_control: false
      show_last_changed: false
      theme: happy
      slider_theme:
        min: 10
        max: 200
        pin: true
        off_when_min: false
        report_when_not_changed: false
      extra_badge:
        entity_id: sensor.my_sensor  # Will take precedence over attribute and unit below.
        attribute: power_consumption
        unit: W
        blacklist_states: 0

light:
  - platform: group
    name: Livingroom Lights
    entities:
      - light.livingroom_tv_lamp
      - light.livingroom_lamp
      - light.front_door

group:
  livingroom_lights:
    name: Livingroom Lights
    view: no
    entities:
      - light.livingroom_tv_lamp
      - light.livingroom_lamp
      - light.front_door 


variable:
  mi_magic_cube_last_event:
    value: 0
    restore: true
    
        
automation:
  - alias: Cube Last Event
    initial_state: True
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id:  mi_magic_cube
    condition:
      condition: template
      value_template: '{{ trigger.event.data.event != 7000 }}'
    action:
      - service:  variable.set_variable
        data_template:
          variable: mi_magic_cube_last_event
          value: '{{ trigger.event.data.event }}'


