homeassistant:
  customize:
    binary_sensor.ping_gateway:
      friendly_name: Gateway (192.168.3.1)
    binary_sensor.ping_access_point:
      friendly_name: AP (192.168.3.10)
    binary_sensor.ping_pi_bedroom:
      friendly_name: Pi Bedroom (192.168.3.250)
    binary_sensor.ping_pi_office:
      friendly_name: Pi Office (192.168.3.209)
    binary_sensor.ping_pi_kitchen:
      friendly_name: Pi Kitchen (192.168.3.247)
    binary_sensor.ping_kodi_livingroom:
      friendly_name: Kodi Livingroom (192.168.3.181)
    binary_sensor.ping_kodi_familyroom:
      friendly_name: Kodi Familyroom (192.168.3.122)
    binary_sensor.ping_pi_familyroom:
      friendly_name: Pi Familyroom (192.168.3.207)
    binary_sensor.ping_pi_livingroom:
      friendly_name: Pi Livingroom (192.168.3.219)
    binary_sensor.ping_pi_phoscon:
      friendly_name: Pi Phoscon (192.168.3.229)
    binary_sensor.ping_pi_internetofthings:
      friendly_name: Pi InternetOfThings (192.168.3.10)
    binary_sensor.ping_pi_outside:
      friendly_name: Pi Outside (192.168.3.139)

binary_sensor:
  - platform: ping
    host: 192.168.3.1
    name: ping_gateway
  - platform: ping
    host: 192.168.3.10
    name: ping_access_point
  - platform: ping
    host: 192.168.3.250
    name: ping_pi_bedroom
  - platform: ping
    host: 192.168.3.209
    name: ping_pi_office
  - platform: ping
    host: 192.168.3.181
    name: ping_kodi_livingroom
  - platform: ping
    host: 192.168.3.247
    name: ping_pi_kitchen
  - platform: ping
    host: 192.168.3.122
    name: ping_kodi_familyroom
  - platform: ping
    host: 192.168.3.207
    name: ping_pi_familyroom
  - platform: ping
    host: 192.168.3.219
    name: ping_pi_livingroom
  - platform: ping
    host: 192.168.3.229
    name: ping_pi_phoscon
  - platform: ping
    host: 192.168.3.10
    name: ping_pi_internetofthings
  - platform: ping
    host: 192.168.3.139
    name: ping_pi_outside

sensor:
  - platform: nzbget
    host: 192.168.3.187
    username: !secret nzbget_username
    password: !secret nzbget_password
    monitored_variables:
      - article_cache
      - download_rate
      - download_paused
      - average_download_rate


###############################################################################
## SNMP Data from linux router.  It calls a custom script to get interface bytes
###############################################################################
  - platform: snmp
    name: snmp_wan_out
    host: 192.168.3.1
    community: !secret snmp_community
    baseoid: .1.3.6.1.4.1.8072.1.3.2.3.1.1.6.79.117.116.112.117.116
  - platform: snmp
    name: snmp_wan_in
    host: 192.168.3.1
    community: !secret snmp_community
    baseoid:    .1.3.6.1.4.1.8072.1.3.2.3.1.1.7.70.111.114.119.97.114.100

###############################################################################
## Current Internet speed.
###############################################################################
  - platform: template
    sensors:
      internet_speed_in:
        friendly_name: 'Internet Speed In'
        value_template: "{{ ((states.input_number.internet_traffic_delta_in.state | float ) / 1000000 ) | round(3) }}"
        unit_of_measurement: 'MB/s'
  - platform: template
    sensors:
      internet_speed_out:
        friendly_name: 'Internet Speed Out'
        value_template: "{{ ((states.input_number.internet_traffic_delta_out.state | float ) / 1000000 )  | round(3) }}"
        unit_of_measurement: 'MB/s'

###############################################################################
# SpeedTest sensor
###############################################################################
  - platform: statistics
    name: 'WAN Traffic IN'
    entity_id: sensor.internet_speed_in
  - platform: statistics
    name: 'WAN Traffic OUT'
    entity_id: sensor.internet_speed_out
  - platform: speedtest
    hour:
      - 2
      - 6
      - 10
      - 14
      - 18
      - 22
    minute:
      - 42
    monitored_conditions:
      - ping
      - download
      - upload

###############################################################################
## PiHole Sensor
###############################################################################
  - platform: pi_hole
    host: 192.168.3.187


group:
  ping_room_assistants:
    name: Ping Room Assistants
    view: no
    entities:
      - binary_sensor.ping_pi_kitchen
      - binary_sensor.ping_pi_livingroom
      - binary_sensor.ping_pi_bedroom
      - binary_sensor.ping_pi_familyroom
      - binary_sensor.ping_pi_office
  ping_kodi_players:
    name: Ping Kodi Players
    view: no
    entities:
      - binary_sensor.ping_kodi_familyroom
      - binary_sensor.ping_kodi_livingroom

  ping_network_equipment:
    name: Ping Network Equipment
    view: no
    entities:
      - binary_sensor.ping_gateway
      - binary_sensor.ping_access_point
      - binary_sensor.ping_pi_internetofthings

  ping_monitoring_equipment:
    name: Ping Monitoring Equipment
    view: no
    entities:
      - binary_sensor.ping_pi_outside

